name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Strip disclaimer from source file
      run:  sed -i '1d' ./software/ventilator-control/diy_06.ino
    - name: Run platformio
      run: platformio run -d ./software/ventilator-control/
